### ISSUE TITLE
can't display widget in vscode

### ISSUE THREAD

**Issue by diamndj** [manzt/anywidget#394]
The hello world example from https://blog.jupyter.org/anywidget-jupyter-widgets-made-easy-164eb2eae102 won't display a widget in a jupyter notebook in vscode. I get a popup asking me to allow downloading of some code and then I get a javascript error that no version of module anywidget is registered.  It works fine if I launch a jupyter notebook from command line and use it with firefox.

details:

```
OS macOS Monterey 12.7.1
vscode 1.4.81
Python extension  2023.20.1
Python 3.11.5
Jupiter vscose extension 2023.10.11
anywidget  0.7.1
```

Cell Code:

```python
import anywidget
import traitlets

class ExampleWidget(anywidget.AnyWidget):
    _esm = """
    export function render({ model, el }) {
        el.classList.add("custom-widget");
        function valueChanged() {
            el.textContent = model.get("value");
        }
        valueChanged();
        model.on("change:value", valueChanged);
    }
    """
    _css = """
    .custom-widget {
        background-color: lightseagreen;
        padding: 0px 2px;
    }
    """
    value = traitlets.Unicode("Hello World").tag(sync=True)

ExampleWidget()
```

Result:

```
Error: No version of module anywidget is registered
    at ph.loadClass (https://file+.vscode-resource.vscode-cdn.net/Users/diamond/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4099813)
    at ph.loadClass (https://file+.vscode-resource.vscode-cdn.net/Users/diamond/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4403287)
    at ph.loadModelClass (https://file+.vscode-resource.vscode-cdn.net/Users/diamond/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4097773)
    at ph._make_model (https://file+.vscode-resource.vscode-cdn.net/Users/diamond/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4094616)
    at ph.new_model (https://file+.vscode-resource.vscode-cdn.net/Users/diamond/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4092246)
    at ph.handle_comm_open (https://file+.vscode-resource.vscode-cdn.net/Users/diamond/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4091039)
    at https://file+.vscode-resource.vscode-cdn.net/Users/diamond/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4402511
    at r._handleCommOpen (https://file+.vscode-resource.vscode-cdn.net/Users/diamond/.vscode/extensions/ms-toolsai.jupyter-2023.10.1100000000-darwin-x64/out/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js:9:114159)
    at async r._handleMessage (https://file+.vscode-resource.vscode-cdn.net/Users/diamond/.vscode/extensions/ms-toolsai.jupyter-2023.10.1100000000-darwin-x64/out/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js:9:116034)
 ```

**Comment by kolibril13** [comment]
I've just tried to reproduce your error like this:

```
python3.11 -m venv .venv && source .venv/bin/activate
pip install ipykernel anywidget
```
then I selected that venv
<img width="516" alt="image" src="https://github.com/manzt/anywidget/assets/44469195/82c75c5d-feaa-4517-b1f5-7d449c17566c">

and pasted the example

```py
import anywidget
import traitlets

class ExampleWidget(anywidget.AnyWidget):
    _esm = """
    export function render({ model, el }) {
        el.classList.add("custom-widget");
        function valueChanged() {
            el.textContent = model.get("value");
        }
        valueChanged();
        model.on("change:value", valueChanged);
    }
    """
    
    _css = """
    .custom-widget {
        background-color: lightseagreen;
        padding: 0px 2px;
    }
    """
    value = traitlets.Unicode("Hello World").tag(sync=True)

ExampleWidget()
```
and I got this result:

<img width="592" alt="image" src="https://github.com/manzt/anywidget/assets/44469195/f1ad5f05-bda7-402a-9fc1-dffadea432c3">

So everything works fine.

Can you double-check that you've picked the right kernel in VS Code?

Also, you can try to restart VS Code and the kernel after installation.

**Comment by manzt** [comment]
> Can you double-check that you've picked the right kernel in VS Code?

Yes, it's key to make sure you have the correct Python environment. Also what version of VS Code are you using?

**Comment by ozekik** [comment]
Hi, thank you for developing this excellent library!
I was experiencing the issue with the Jupyter extension (v2023.10.1100000000) on VS Code (v1.84.2).
I found that in some cases the same _JavaScript_ (not Python) part of the widget works in standard JupyterLab but not in VS Code Jupyter, and that it is often hard to spot the cause for most JavaScript issues are logged vaguely just as reported above.
In my case, the issue resolved itself when I switched from a hatch-based project to a poetry-based one, though the exact reason remains unclear.

**Comment by diamndj** [comment]
I was getting a popup in vscode somewhat intermittently asking me to allow it to download some javascript.

When I clicked on 'more info' instead of allow, it took me to https://github.com/microsoft/vscode-jupyter/wiki/IPyWidget-Support-in-VS-Code-Python, which recommends adding the line  
"jupyter.widgetScriptSources": ["jsdelivr.com", "unpkg.com"],

to my settings.json file. After doing this and restarting vscode, it seems to work now. 

It seems like maybe something is not working correctly with that popup, but adding those 2 sources allowed vscode to find the right widget?

Thanks everybody for your prompt responses and your help!

**Comment by manzt** [comment]
> It seems like maybe something is not working correctly with that popup, but adding those 2 sources allowed vscode to find the right widget?

Hmm, I'm not sure I am able to reproduce but thank you for sharing your solution. Yes, both VS Code and Colab require getting the anywidget front-end code from a CDN (e.g., `jsdevlir.com` or `unpkg.com`), while in Jupyter/JupyterLab the front-end code is loaded from the local file system from the Jupyter data files. I would "Allow" the JS when prompted in this context.

**Comment by manzt** [comment]
> In my case, the issue resolved itself at some point when I switched from a hatch-based project to a poetry-based one, though the exact reason remains unclear.

My hunch is that this is likely not an issue with the Python build system, but rather VS Code's discovery of the anywidget front-end code.
