### ISSUE TITLE
Widget using chart.js zoomPlugin not working in VSCode

### ISSUE THREAD

**Issue by eimrek** [manzt/anywidget#506]
Hi, thanks for anywidget, great project!

I want to make a Jupyter widget from a javascript tool that uses `chart.js` and some plugins, including the `chartjs-plugin-zoom`. The latter seems to be causing problems in the VSCode visualizer. Everything works well in chrome-based jupyter notebook and lab environments. Perhaps you could offer some advice on what could be the issue. 

Minimal way to reproduce:

Bootstrap with `npm create anywidget@latest`, making a Vanilla Javascript project with esbuild.

```
npm install chartjs-plugin-zoom
```
Just add the import in `widget.js`, nothing else:

```
import zoomPlugin from "chartjs-plugin-zoom";
```

No errors are raised in (chrome-based) Jupyter notebook and lab and the default `Counter()` widget works well.

In VSCode, however, I get errors. In the "Developer Tools" log:

![image](https://github.com/manzt/anywidget/assets/8721264/6df62bfd-dad1-4d00-b744-baaa18cc28ba)

<details>
  <summary>See full log:</summary>

```
ipywidgetsKernel.js:18 Failed to to Widget load class anywidgetAnyView {className: 'AnyView', moduleName: 'anywidget', moduleVersion: '0.9.3', error: Error: No version of module anywidget is registered
    at ph.loadClass (https://file+.vscode-resou…, timedout: false, …}
handleLoadError @ ipywidgetsKernel.js:18
X.emit @ ipywidgetsKernel.js:3
handleLoadError @ ipywidgetsKernel.js:18
await in handleLoadError (async)
errorHandler @ ipywidgetsKernel.js:18
sendError @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
Promise.catch (async)
loadClass @ ipywidgets.js:2
loadViewClass @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
Promise.then (async)
create_view @ ipywidgets.js:2
renderWidget @ ipywidgetsKernel.js:18
await in renderWidget (async)
Jh @ ipywidgetsKernel.js:18
await in Jh (async)
(anonymous) @ ipywidgetsKernel.js:18
Promise.then (async)
Gh @ ipywidgetsKernel.js:18
Hh @ ipywidgetsKernel.js:18
renderOutputItem @ ipywidgetsRenderer.js:2
await in renderOutputItem (async)
renderOutputItem @ notebookWebviewPreloads.js:3
await in renderOutputItem (async)
h @ notebookWebviewPreloads.js:3
render @ notebookWebviewPreloads.js:3
render @ notebookWebviewPreloads.js:3
renderOutputElement @ notebookWebviewPreloads.js:3
renderOutputCell @ notebookWebviewPreloads.js:3
await in renderOutputCell (async)
(anonymous) @ notebookWebviewPreloads.js:3
c.set.queue @ notebookWebviewPreloads.js:3
enqueue @ notebookWebviewPreloads.js:3
(anonymous) @ notebookWebviewPreloads.js:3
postMessage (async)
(anonymous) @ index.html?id=af08c3c2-28b3-4882-aeca-f25d3654d135&origin=2cf27bbd-fbb7-490e-b154-cd389776685c&swVersion=4&extensionId=&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&purpose=notebookRenderer:1190
HostMessaging.channel.port1.onmessage @ index.html?id=af08c3c2-28b3-4882-aeca-f25d3654d135&origin=2cf26bbd-fbb7-490e-b154-cd389776685c&swVersion=4&extensionId=&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&purpose=notebookRenderer:312
ipywidgets.js:2 Error: No version of module anywidget is registered
    at ph.loadClass (ipywidgets.js:2:4099813)
    at ph.loadClass (ipywidgets.js:2:4403287)
    at ph.loadViewClass (ipywidgets.js:2:4097946)
    at ipywidgets.js:2:4090018
    at async lt.renderWidget (ipywidgetsKernel.js:18:15907)
    at async Jh (ipywidgetsKernel.js:18:29681)
loadViewClass @ ipywidgets.js:2
await in loadViewClass (async)
(anonymous) @ ipywidgets.js:2
Promise.then (async)
create_view @ ipywidgets.js:2
renderWidget @ ipywidgetsKernel.js:18
await in renderWidget (async)
Jh @ ipywidgetsKernel.js:18
await in Jh (async)
(anonymous) @ ipywidgetsKernel.js:18
Promise.then (async)
Gh @ ipywidgetsKernel.js:18
Hh @ ipywidgetsKernel.js:18
renderOutputItem @ ipywidgetsRenderer.js:2
await in renderOutputItem (async)
renderOutputItem @ notebookWebviewPreloads.js:3
await in renderOutputItem (async)
h @ notebookWebviewPreloads.js:3
render @ notebookWebviewPreloads.js:3
render @ notebookWebviewPreloads.js:3
renderOutputElement @ notebookWebviewPreloads.js:3
renderOutputCell @ notebookWebviewPreloads.js:3
await in renderOutputCell (async)
(anonymous) @ notebookWebviewPreloads.js:3
c.set.queue @ notebookWebviewPreloads.js:3
enqueue @ notebookWebviewPreloads.js:3
(anonymous) @ notebookWebviewPreloads.js:3
postMessage (async)
(anonymous) @ index.html?id=af08c3c2-28b3-4882-aeca-f25d3654d135&origin=2cf26bbd-fbb7-490e-b154-cd389776685c&swVersion=4&extensionId=&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&purpose=notebookRenderer:1190
HostMessaging.channel.port1.onmessage @ index.html?id=af08c3c2-28b3-4882-aeca-f25d3654d135&origin=2cf26bbd-fbb7-490e-b154-cd389776685c&swVersion=4&extensionId=&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app&purpose=notebookRenderer:312
```

</details>

**Comment by jakobtroidl** [comment]
I think I had a similar issue recently! If I remember correctly, I was able to resolve it by running the following code as was stated in the README. 

```bash
python -m pip install --upgrade pip
pip install -e ".[dev]"
```

**Comment by eimrek** [comment]
Thanks for the comment!

Unfortunately, this doesn't seem to work. I have tested with completely new up-to-date environments with python 3.10 and 3.11, the same errors occur. I think there is something in the `chartjs-plugin-zoom` package that doesn't work well with anywidget and vscode jupyter editor. 

Note that our legacy version (using `jupyter_packaging`, ...) worked well with vscode (core js is the same).

**Comment by manzt** [comment]
Hi there, this doesn't appear to be an issue with anywidget itself but rather a quirk of this specific JS dependency. Specifically, it looks like an issue with the `chartjs-plugin-zoom` dependency and how it is processed with esbuild. 

My hunch is that there is some behavior you relied upon with your previous webpack config (in the `jupyter_packaging` usage) that needs replication with `esbuild`. For example, see [this solution](https://github.com/manzt/anywidget/issues/369#issuecomment-1792376003) for using Deck.gl. I'm not familiar with this specific dependency, so I'm afraid I can't speculate beyond this.

**Comment by kolibril13** [comment]
Hi there!
in Jupyter Tldraw, I get the same error "Failed to load view class 'AnyView' from module 'anywidget' " in VSCode as well.
Interestingly, it only occurs the *second* time I run that cell.

https://github.com/manzt/anywidget/assets/44469195/6023e378-5338-4f8a-ab9a-4987cfda5817


Here's the code for that widget https://github.com/kolibril13/jupyter-tldraw/blob/main/demo_basic.ipynb
```jsx
import * as React from "react";
import { createRender, useModelState } from "@anywidget/react";
import { Tldraw } from "@tldraw/tldraw";
import "@tldraw/tldraw/tldraw.css";
import "./widget.css";

const render = createRender(() => {
  const [width] = useModelState("width");
  const [height] = useModelState("height");
  return (
    <div
      style={{
        position: "relative",
        width: width,
        height: height,
      }}
    >
      <Tldraw />
    </div>
  );
});

export default { render };
```
